import Constant from './Constant';

export default {
  SEND_OTP: Constant.API_BASEURL + 'SendOTP',
  VERIFY_OTP: Constant.API_BASEURL + 'VerifyOPT',
  GET_CATEGORY: Constant.API_BASEURL + 'CategoryList',
  GET_BANNER: Constant.API_BASEURL + 'Banner',
  GET_SUB_CATEGORY: Constant.API_BASEURL + 'PosterList',
  GET_SAVED_POSTER: Constant.API_BASEURL + 'ViewSavedPoster',
  GET_POST_DETAILS: Constant.API_BASEURL + 'PosterDetails',
  VIEW_PROFILE: Constant.API_BASEURL + 'ViewProfile',
  UPDATE_PROFILE: Constant.API_BASEURL + 'UpdateProfile',
  GET_BALANCE: Constant.API_BASEURL + 'GetBalance',
  GET_HISTORY: Constant.API_BASEURL + 'TransactionList',
  GET_PURCHASE: Constant.API_BASEURL + 'PurchasePoster',
  POSTER_SAVE: Constant.API_BASEURL + 'SavePoster',
  PURCHASE_POINT: Constant.API_BASEURL + 'PurchaseMembership',
  PROMO_CODE: Constant.API_BASEURL + 'CheckPromocode',
  GET_NEW_DATE: Constant.API_BASEURL + 'NewArrival',
  GET_MONTH_DATE: Constant.API_BASEURL + 'ThisMonth',
  GET_GUIDE_URL: Constant.API_BASEURL + 'Guide',
  QandA: Constant.API_BASEURL + 'QandA',
  UserStatus: Constant.API_BASEURL + 'UserStatus',
  CategoryList: Constant.API_BASEURL + 'CategoryList',
  RegisterUser: Constant.API_BASEURL + 'RegisterUser',
  EditRegistration: Constant.API_BASEURL + 'EditRegistration',
  GetPrice: Constant.API_BASEURL + 'GetPrice',
  GetCity: Constant.API_BASEURL + 'CityList',
  GetState: Constant.API_BASEURL + 'StateList',
  MEETING_ID: Constant.API_BASEURL + 'MeetingID',
  LIVE_USER: Constant.API_BASEURL + 'LiveCounter',
  LOG_BOOK: Constant.API_BASEURL + 'Logbook',
  PRE_MAKEUP: Constant.API_BASEURL + 'PreImage',
  POST_MAKEUP: Constant.API_BASEURL + 'PostImage',
};
